# To run dgl_ptm on an infra with NVIDIA GPUs, you need to install cuda version
# of dgl. This environment file specifies the dgl conda channel and cuda version
# of dgl.
name: dgl_ptm_cuda
channels:
  - defaults
dependencies:
  - dglteam/label/cu121::dgl
  - pip:
    - -e ./dgl_ptm
