name: dgl_ptm
channels:
  - defaults
  - nvidia
dependencies:
  - python=3.11
  - numpy
  - scipy=1.10.1
  - pydantic>=2
  - pytorch::pytorch==2.1.1
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch::pytorch-cuda=12.1
  - xarray
  - zarr
  - dask
  - pip
  - dglteam::dgl=1.1.3 #for CPU
  # - dglteam/label/cu121::dgl #for GPU
  - pip:
    - -e ./dgl_ptm
