name: dgl_ptm
channels:
  - defaults
dependencies:
  - python>=3.10
  - pip
  - numpy
  - scipy=1.10.1
  - pytorch::pytorch==2.1.0
  - pytorch::torchvision==0.16.0
  - pytorch::torchaudio==2.1.0
  - dglteam::dgl==1.1.3
  - xarray
  - ipykernel
  - pyyaml
  - zarr
  - pip:
    - -e ../dgl_ptm

