name: dgl_ptm_gpu
channels:
  - defaults
  - nvidia
dependencies:
  - python=3.11
  - numpy
  - scipy=1.10.1
  - xarray
  - zarr
  - pytorch::pytorch=2.1.1
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch::pytorch-cuda=12.1
  - pip:
    - https://data.dgl.ai/wheels/cu121/dgl-2.0.0%2Bcu121-cp311-cp311-manylinux1_x86_64.whl
    - -e ../dgl_ptm
