name: Linting

on:
  pull_request:  # only run on pull requests for now
    branches: [ "master", "development" ]

jobs:
  lint:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./dgl_ptm
      steps:
        - uses: actions/checkout@v3
        - name: Set up Python 3.11
          uses: actions/setup-python@v3
          with:
            python-version: "3.11"
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            python -m pip install .[dev]
        - name: Get changed files in dgl_ptm folder  # for now, we only lint the changed files
          id: dgl_ptm
          run: |
            echo "::set-output name=dgl_ptm::$(git diff --name-only origin/${{ github.base_ref }}...HEAD | grep '^dgl_ptm/')"
        - name: Check source code style against standards
          run: ruff check ${{ steps.dgl_ptm.outputs.dgl_ptm }}
        - name: Get changed files in tests folder  # for now, we only lint the changed files
          id: tests
          run: |
            echo "::set-output name=tests::$(git diff --name-only origin/${{ github.base_ref }}...HEAD | grep '^tests/')"
        - name: Check tests code style against standards
          run: ruff check ${{ steps.tests.outputs.tests }}