name: Linting

on:
  pull_request:  # only run on pull requests for now
    branches: [ "master", "development" ]

jobs:
  lint:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./dgl_ptm
      steps:
        - uses: actions/checkout@v3
        - name: Set up Python 3.11
          uses: actions/setup-python@v3
          with:
            python-version: "3.11"
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            python -m pip install .[dev]
        - name: Get changed files  # for now, we only lint the changed files
          id: files
          run: |
            echo "::set-output name=files::$(git diff --name-only origin/${{ github.base_ref }}...HEAD)"
        - name: Check code style against standards
          run: ruff check ${{ steps.files.outputs.files }}